### PR TITLE
scrape records

### PR DESCRIPTION
**Pull request by bendikjohansen**

### CODE REVIEW

**Comment by bendikjohansen** [comment]
This pull request is meant to resolve #48.

**Review by sungyeonu — CHANGES_REQUESTED** [review]
Looks good!

One change I would like to request is that in the JSON files, the keys should have underscore instead of space. This is to prevent some languages not being able to fetch the data correctly.  For example, "Aloha K.K." should be "Aloha_K.K". Then each key should have "name" tag, and in here spaces are fine. Do you mind fixing this error?

**Comment by sungyeonu** [comment]
Some help: 
item_key = name.replace(" ", "_").replace("-", "_")
name = tr("td")[0].text.strip()

**Comment by sungyeonu** [comment]
Looks good to me! Thank you for your contribution!

**Comment by bendikjohansen** [comment]
I'm happy to able to help! Please consider closing #48 as a result of this pull request.

**Pull request merged**
