### PR TITLE
Pretty print the JSON files

### PR DESCRIPTION
**Pull request by antriver**
This makes the generated .json files far more readable, and makes it easy to see what's changed when you scrape again to update the data.

### CODE REVIEW

**Comment by sungyeonu** [comment]
GREAT! 

seems like the only change was at util.py, adding an indent. I recently made edits to scrapy.py and util.py. Could you review again so there are no conflicts?
json.dump(itemList, f, indent=4)

**Comment by sungyeonu** [comment]
Oh you just made a new PR. let me have a look

**Comment by antriver** [comment]
That's right, adding the `indent=4` was the only real change. Thanks for taking a look!

**Comment by sungyeonu** [comment]
Brilliant work Anthony. No more going to jsonformatter.org for me!

**Pull request merged**
